{% set name = "gdk-pixbuf" %}
{% set version_maj = "2.36" %}
{% set version = "2.36.11" %}
{% set sha256 = "ae62ab87250413156ed72ef756347b10208c00e76b222d82d9ed361ed9dde2f3" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    fn: {{ name }}-{{ version }}.tar.xz
    sha256: {{ sha256 }}
    url: http://ftp.gnome.org/pub/gnome/sources/{{ name }}/{{ version_maj }}/{{ name }}-{{ version }}.tar.xz
    patches:
      - 0001-changed-perl-script-to-use-env.patch

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - toolchain
    - python <3
    - m4
    - autoconf
    - automake
    - libtool
    - pkg-config
    - perl
    - glib >=2.51
    - gobject-introspection
    - libffi
    - libtiff
    - libpng
    - jpeg
    - gettext  # [osx]
  run:
    - libgcc  # [linux]
    - glib >=2.51
    - gobject-introspection
    - libffi
    - libtiff
    - libpng
    - jpeg
    - gettext  # [osx]

test:
  commands:
    - gdk-pixbuf-csource --version
    - gdk-pixbuf-query-loaders --help
    - gdk-pixbuf-pixdata --help

about:
  home: https://developer.gnome.org/gdk-pixbuf/ 
  license: GPL-2.0
  license_family: GPL
  license_file: COPYING
  summary: "GdkPixbuf is a library for image loading and manipulation."

extra:
  recipe-maintainers:
    - notestaff
